node{

//dir ('/home/labuser/Documents/'){

def mvnHome
def dockerHome
stage('checkout') 

{
    //build 'checkout'
    git 'https://github.com/bhaskar-498135/bootcamp.git'
    
    mvnHome = tool 'maven-3'
    dockerHome = tool 'docker'
}

stage('build and test') {
    
    dir('cicd-pipeline-dj'){
    
   withEnv(["MVN_HOME=$mvnHome"]) {
            
            
                sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore clean package'
            
        }
    }
}

stage('create docker images') {
    
    dir('cicd-pipeline-dj'){
    withEnv(["DOCKER_HOME=$dockerHome"]) {
    
    sh '"$DOCKER_HOME/bin/docker" build -t mavurubhaskar/bootcamp-war:1.0 .'
}
}
}

stage('push docker images') {
    
    dir('cicd-pipeline-dj'){
   
   withEnv(["DOCKER_HOME=$dockerHome"]) { 
    withCredentials([string(credentialsId: 'dockerpwd', variable: 'dockercred')]) {
    
    
    sh "docker login -u mavurubhaskar -p ${dockercred}"
}
    
    
    sh 'docker push mavurubhaskar/bootcamp-war:1.0'
   }
}

}

stage('run docker images') {
    
     sh 'docker run -p 8888:8080 -d mavurubhaskar/bootcamp-war:1.0'
}
    
//}
}
